### PR TITLE
Fix/issue 129

### LINKED ISSUE #129: wc_orders_count Fatal Error
#### What I expected

Updating to version 1.4.5 goes smoothly.

#### What happened instead

When a user updates to 1.4.5, some of them are getting fatal errors like this: 

http://cld.wthms.co/6Dw10m
Image link: http://cld.wthms.co/6Dw10m

Here are cases where this is happening:

* 1515672-zen
* https://wordpress.org/support/topic/fatal-error-on-latest-update-5/
* https://wordpress.org/support/topic/1-4-5-500-error-fatal-error-undefined-function-wc_orders_count/
* https://wordpress.org/support/topic/error-500-after-1-4-5/

#### Steps to reproduce the issue

1. Update to version 1.4.5
2. Doesn't matter if you're on version 3.4.7 or 3.5.0 of WooCommerce, issue remains.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by c-shultz**
Fixes #129 

#### Changes proposed in this Pull Request:
- ~Adds `woo-includes` and checks `is_woocommerce_active()` before loading plugin~
- Check for 'WooCommerce' class exists (thanks @superdav42)
- Rebuilding .pot

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? Make sure you ran `grunt` before creating this Pull Request.

### CODE REVIEW

**Comment by roykho** [comment]
@c-shultz  This may not be good idea. We're trying to remove woo-includes in all extensions coming future.

**Comment by roykho** [comment]
What David suggested is how Stripe does it as well.

**Comment by c-shultz** [comment]
That would clean this change up tremendously. Do you know why woo-includes used such a complex solution (scanning the `active_plugins` option)?

**Comment by superdav42** [comment]
Scanning active_plugins will work in any context while class_exists will only work after `plugins_loaded`. Of course if your are going to use any WooCommerce classes or functions you will need to wait for `plugins_loaded` anyway.

**Pull request merged**
