### PR TITLE
Implementation for Gtag.js

### LINKED ISSUE #112: use Global Site Tag tracking to be compatible with free "Google Analytics Dashboard for WordPress"
Changelog is here:
https://deconf.com/adding-gtag-js-to-your-site/
From the changelog: If you’re using an Ecommerce tracking plugin, make sure the plugin supports the new Global Site Tag tracking code.

So i expect that you in free and paid version of woocommerce-google-analytics-integration
use Global Site Tag tracking to be compatible with free "Google Analytics Dashboard for WordPress".

Thank you

### PR DESCRIPTION
**Pull request by bor0**
Fixes #112.

PR based on documentation https://developers.google.com/analytics/devguides/collection/gtagjs/migration

#### Changes proposed in this Pull Request:
- Gtag implementation for Analytics

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? Make sure you ran `grunt` before creating this Pull Request.

### CODE REVIEW

**Comment by laurendavissmith** [comment]
@bor0 what are the testing instructions for this one to ensure it's working

**Comment by bor0** [comment]
I would start by trying with Gtag disabled (make sure you get results in analytics.google.com), and also with Gtab enabled. After I had it enabled, it was successfully sending data to Gtag Analytics but I haven't been able to find any results on analytics.google.com.

Maybe we can poke someone that has more experience with this?

**Comment by johndcoy** [comment]
I'd suggest the option to *Enable Universal Analytics* be enabled by default. If not, it appears Standard Ecommerce data is not traced in GA:

http://cld.wthms.co/6ntzNC

I would think majority installing a specific WooCommerce GA plugin should assume this feature is already enabled to track Standard Ecommerce data. I'd also suggest defaulting the *Enable Enhanced eCommerce* option as well - just because :) . However, neither ecommerce data however appears to show unless *Enable Universal Analytics* is enabled.

I had to wait hours for the data to pull into GA initially. I then immediately placed an order after enabling Universal Analytics, and I see the same Ecommerce information page in the GA dashboard. It's likely I'll have to wait again for Universal Analytics to propagate Standard ecommerce data, right?

**Comment by bor0** [comment]
@budzanowski I think so, but we can close it for now and come back to it later when we have the chance. This PR can at least be used as a reference.

**Pull request closed without merging**
