### PR TITLE
Remove unused function from formatters

### PR DESCRIPTION
**Pull request by tomalec**
### Changes proposed in this Pull Request:

Remove three unused functions that seem to be leftovers from the old implementation:
- trackChangeCartItemQuantity
- trackException
- trackEvent

### Checks:

* [x] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Detailed test instructions:

1. Double-check that none of those functions is used in the code
2. Smoke test

### Changelog entry

> Dev - Remove unused functions from code.

### CODE REVIEW

**Review by puntope — APPROVED** [review]
✅  LGTM

For the `trackChangeCartItemQuantity` seems like `change_cart_quantity` is not supported anymore by GA?

**Comment by mikkamp** [comment]
Another one that doesn't seem to be used is `add_shipping_info`. Can we confirm if it was the intention to include this information during either `begin_checkout` or the `purchase` event?

**Comment by puntope** [comment]
Re- Cart item quantity https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/312

**Comment by tomalec** [comment]
@martynmjones Could you confirm regarding car quantities?

**Comment by martynmjones** [comment]
> Another one that doesn't seem to be used is `add_shipping_info`. Can we confirm if it was the intention to include this information during either begin_checkout or the purchase event?

>  @martynmjones Could you confirm regarding car quantities?

We weren't previously tracking quantity changes or shipping info. Both those events had been added in the initial integration with Blocks in core but in testing neither were reliable and we didn't have an alternative for classic.

So as the extension was already not tracking those events we're safe to remove them. We can then look into alternatives at a later date if we decide we want to track the additional information.

**Comment by tomalec** [comment]
@martynmjones, and what about [tracking shipping and `add_shipping_info`](https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/375#issuecomment-1987887419)? 
Previously we were tracking it in https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/322/files#diff-aa47bb8c923774f3c31519cb78bd1ae693f025fe39846d2571eb13640b399a87L64-L74

Should we add `checkout-set-shipping-address` to blocks.js?

**Comment by martynmjones** [comment]
Sorry Tomek, I wasn't clear in my previous reply. The `add_shipping_info` event was only added in the core integration for Blocks and then copied over when we moved [tracking for Blocks to the extension](https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/269).

Before that it didn't exist in the extension and there was never an equivalent for classic pages so I think we're safe to remove it.

**Pull request merged**
